# Generated by Django 3.2.7 on 2024-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(default='https://eprint.iacr.org/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_id',
            field=models.CharField(default='NULL', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
